package com.dimakers.fitoryapp;

import com.dimakers.fitoryapp.api.models.Club;
import com.dimakers.fitoryapp.api.models.Metodo;
import com.dimakers.fitoryapp.api.models.MetodosPago;
import com.dimakers.fitoryapp.api.models.SesionFull;
import com.dimakers.fitoryapp.api.models.SesionFullMes;
import com.dimakers.fitoryapp.api.models.SubscripcionFreeFull;
import com.dimakers.fitoryapp.api.models.Sucursal;
import com.dimakers.fitoryapp.api.models.SucursalFull;

import java.util.ArrayList;

public class Variables {
//    public final static String HOST = "http://192.168.1.70:8000/";
//    public final static String HOST = "http://192.168.1.132:8000/";
    public final static String HOST = "https://fitory.com/";
    public final static String TOKEN_API = "f55a0816690cb919f940993f806a6c5ef3f4a555";
    public final static String MEDIA_URL = HOST+ "media/";
    public final static String PREFERENCES = "MyPrefs";
    public final static String USERNAME = "username";
    public final static String TOKEN = "token";
    public final static String IDUSER = "idUser";
    public final static String CLUBDETALLE = "clubDetalle";
    public final static String SUCURSALDETALLE = "sucursalDetalle";
    public final static String CLIENTEID = "idCliente";
    public final static String CLIENTENOMBRE = "nombreCliente";
    public final static String CLIENTEAPELLIDO = "apellidoCliente";
    public final static String CLIENTEGENERO = "generoCliente";
    public final static String CLIENTEOBJETIVO = "objetivoCliente";
    public final static String EMAIL = "email";
    public final static String FBID = "fbid";
    public final static String GOOGLEID = "googleid";
    public final static String PERMISSION_PREFERENCE = "PERMISSION_PREFERENCE";
    public final static String PERMISSION_LOCATION = "PERMISSION_LOCATION";
    public final static String LATITUD = "LATITUD";
    public final static String LONGITUD = "LONGITUD";
    public final static String TELEFONO = "TELEFONO";
    public final static String FOTO = "FOTO";
    public final static int REQUEST_ACTION_GET_CONTENT = 777;
    public final static int REQUEST_IMAGE_CAPTURE =776;
    public final static String PROFILE_PIC = "PROFILE_PIC";
    public final static String SOCIAL_MEDIA = "SOCIAL_MEDIA";
    public final static String HORARIO = "horarios";
    public final static String ACTIVIDADES = "actividades";
    public final static String BEACON = "beacon";
    public final static String OBJETIVO = "objetivo";
    public final static String MAYOR = "mayor";
    public final static String MENOR = "menor";
    public final static String SUCURSAL_ID = "sucursal_id";
    public final static String SELECCIONUBICACION = "seleccion_ubicacion";
    public final static String CIUDADID = "ciudad_id";
    public final static String ESTADOID = "estado_id";
    public final static String SUCURSALES = "sucursales";
    public final static String SESIONES = "sesiones";
    public final static String SUSCRIPCION = "suscripcion";
    public static final String LOCATION = "location";
    public static final String CIUDAD = "ciudad";
    public static final String EVALUACION = "evaluacion";
    public static ArrayList<Sucursal> sucursales = new ArrayList<>();
    public static ArrayList<Sucursal> sucursalesFavs = new ArrayList<>();
    public static ArrayList<Club> clubs;
    public static ArrayList<SucursalFull> sucursalFulls = new ArrayList<>();
    public static ArrayList<SesionFull> sesionFulls = new ArrayList<>();
    public static ArrayList<SesionFullMes> sesionFullsMes = new ArrayList<>();
    public static ArrayList<SubscripcionFreeFull> subscripcionFreeFulls = new ArrayList<>();
    public static ArrayList<Metodo> metodos  = new ArrayList<>();
//    public static boolean is_running = false;
}
